name: Project CI
run-name: "Actions run # ${{github.run_number}} by ${{github.actor}}"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    
jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
    - name: Step 1. List files
      run: ls
    - name: Step 2. Checkout main branch
      uses: actions/checkout@v3
    - name: Step 3. Setup Java JDK
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 1.17
    - name: Step 4. Build the Jakarta web app
      run: echo mvn -B package --file pom.xml
    - name: Step 5. Get Execution Policy
      run: Get-ExecutionPolicy
    - name: Step 6. List environment variables:
      run: env
  build-on-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Step 1. Log the prebuild disk space
        run: df
      - uses: actions/checkout@v3
        name: Step 2. Checkout the main branch
      - name: Step 3. Setup JDK v1.17
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 1.17
      - name: Step 4. Build Jakarta web app with Maven
        run: echo mvn -B package --file pom.xml
      - name: Step 5. Build the Android native app
        run: |
          echo the ANDROID_SDK_ROOT
          echo $ANDROID_SDK_ROOT
      - name: Step 6. Run Selenium tests
        run: |
          echo the SELENIUM_JAR_PATH
          echo $SELENIUM_JAR_PATH
      - name: Step 7. Log Build tools versions
        run: |
          mvn --version
          ant -version
          gradle --version
          git --version
      - name: Step 8. Log the postbuild disk space
        run: df


