name: Project CI
run-name: "Actions run # ${{github.run_number}} by ${{github.actor}}"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run single line script
        run: echo Running build
      - name: Run multi-line script
        run: |
          echo Checking directory contents with ls
          ls -a
          echo
          echo Is Java installed?
          java -version
          echo
          echo Is Gradle installed?
          gradle --version
          echo
          echo Is Maven installed?
          mvn --version
          echo
          echo Is Ant installed?
          ant -version
          echo
