name: Project CI
run-name: ${{github.actor}} is using Github Actions
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run single line script
        run: echo Running build
      - name: Run multi-line script
        run: |
          echo Build project
          echo test, deploy to staging
