name: Project CI
run-name: "Actions run # ${{github.run_number}} by ${{github.actor}}"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run single line script
        run: echo Running build
      - name: Run multi-line script
        run: |
          echo 1. Checking directory contents with ls
          ls -a
          echo
          echo 2. Is Java installed?
          java -version
          echo
          echo 3. Is Git installed?
          git --version
          echo
          echo 4. What Build tools are instlled?
          mvn --version
          gradle --version
          ant -version
          echo
          echo 5.
          echo 6.
          echo 7.
          echo 8. Who is running this script?
          whoami
          echo
          echo 9. How is the disk laid out?
          df
          echo
          echo 10. Which environment variables are available?
          env

